version: '3.8'

services:
  sql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${SQL_SA_PASSWORD}
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "${SQL_SA_PASSWORD}" -Q "SELECT 1" -b -o /dev/null
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 10s
    restart: unless-stopped

  api:
    build:
      context: .
      dockerfile: TournamentOrganizer/TournamentOrganizer/Dockerfile
    image: timiraca/tournament_organizer_api:latest
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ConnectionStrings__DefaultConnection=Server=sql;Database=TournamentOrganizer;User Id=sa;Password=${SQL_SA_PASSWORD};TrustServerCertificate=True
    depends_on:
      sql:
        condition: service_healthy
    restart: unless-stopped

volumes:
  sql_data:
    driver: local