version: '3.9'

services:
  webapi:
    image: timiraca/tournament-organizer-api:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Server=db;Database=TournamentDb;User Id=sa;Password=YourSecurePassword!
    ports:
      - "80:80"
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - SA_PASSWORD=YourSecurePassword!
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
