services:
  tournamentorganizer.api:
    image: ${DOCKER_REGISTRY-}tournamentorganizerapi
    build:
      context: .
      dockerfile: TournamentOrganizer/Dockerfile
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Server=db;Database=TournamentDb;User=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True
    volumes:
      - ~/.aspnet/https:/https:ro
    depends_on:
      - db
    networks:
      - app-network

  frontend:
    build:
      context: ../tournamentorganizer-react
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=/api
    depends_on:
      - tournamentorganizer.api
    networks:
      - app-network

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong!Passw0rd
      - MSSQL_PID=Express
    volumes:
      - sqldata:/var/opt/mssql
    networks:
      - app-network
  

networks:
  app-network:
    driver: bridge

volumes:
  sqldata: