name: Deploy Tournament Organizer API

on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.7.1

      - name: Docker Login
        # You may pin to the exact commit or the version.
        # uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567
        uses: docker/login-action@v3.3.0
        with:
          # Username used to log against the Docker registry
          username: ${{ secrets.CONTAINER_REGISTRY_USERNAME }}
          # Password or personal access token used to log against the Docker registry
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push API image
        run: |
          docker build -t timiraca/tournament_organizer_api:latest -f TournamentOrganizer/Dockerfile .
          docker push timiraca/tournament_organizer_api:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment: production

    steps:
      - name: Check out repository
        uses: actions/checkout@v4.2.2

      - name: Set up Docker Compose
        uses: docker/compose-action@v2
        with:
          context: .
          files: docker-compose.yml
          project-name: tournament-organizer

      - name: Deploy using Docker Compose
        env:
          DB_CONNECTION_STRING: ${{ secrets.DB_CONNECTION_STRING }}
        run: docker compose up -d
