name: Deploy Tournament Organizer API
on:
  push:
    branches:
      - main 
jobs:
  build:
    runs-on: ubuntu-latest
    environment: container
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.7.1
      
      - name: Docker Login
        uses: docker/login-action@v3.3.0
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        
      - name: Build and push API image
        uses: docker/build-push-action@v5
        with:
          context: ./TournamentOrganizer
          file: ./TournamentOrganizer/TournamentOrganizer/Dockerfile
          push: true
          tags: timiraca/tournament_organizer_api:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment: production
    steps:
      - name: Check out repository
        uses: actions/checkout@v4.2.2
      
      - name: Deploy using Docker Compose
        env:
          DB_CONNECTION_STRING: ${{ secrets.DB_CONNECTION_STRING }}
        run: |
          docker compose pull
          docker compose up -d
