name: Deploy ASP.NET Web API to DockerHub

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: Container

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t timiraca/tournamentorganizer:latest .
          docker push timiraca/tournamentorganizer:latest

      - name: Deploy with Docker Compose
        run: |
          docker-compose -f docker-compose.yml up -d
